wandb_version: 1

batch_size:
  value: 16
chain:
  value: random
iterations:
  value: 10000
n_embd:
  value: 16
n_head:
  value: 1
n_layer:
  value: 2
order:
  value: 1
seed:
  value: 1
sequence_length:
  value: 128
