wandb_version: 1

batch_size:
  desc: null
  value: 16
chain:
  desc: null
  value: random
iterations:
  desc: null
  value: 10000
n_embd:
  desc: null
  value: 16
n_head:
  desc: null
  value: 1
n_layer:
  desc: null
  value: 2
order:
  desc: null
  value: 2
seed:
  desc: null
  value: 1
sequence_length:
  desc: null
  value: 128
config_format:
  desc: null
  value: markov
acc_steps:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.002
warmup_percent:
  desc: null
  value: 0.02
weight_decay:
  desc: null
  value: 0.001
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
scheduler:
  desc: null
  value: cos
opt:
  desc: null
  value: adamw
eval_freq:
  desc: null
  value: 1
results_base_folder:
  desc: null
  value: ./exps
grad_clip:
  desc: null
  value: 0.0
dataset:
  desc: null
  value: markov
vocab_size:
  desc: null
  value: 2
data_in_ram:
  desc: null
  value: false
model:
  desc: null
  value: base
use_pretrained:
  desc: null
  value: none
dropout:
  desc: null
  value: 0
dtype:
  desc: null
  value: torch.float16
bias:
  desc: null
  value: false
no_compile:
  desc: null
  value: true
wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: bias-test
wandb_run_prefix:
  desc: null
  value: none
eval_seq_prefix:
  desc: null
  value: '0'
distributed_backend:
  desc: null
  value: null
p:
  desc: null
  value: 0.5
q:
  desc: null
  value: 0.5
memory:
  desc: null
  value: -1
initial:
  desc: null
  value: uniform
init:
  desc: null
  value: base
init_value:
  desc: null
  value: 1.0
world_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724804325.107941
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
